
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVleftMODPOWleftLBRRBRnonassocNEGADD DIV LBR MOD MUL NUM POW RBR SUBexpr : expr ADD exprexpr : expr SUB exprexpr : expr MUL exprexpr : expr DIV exprexpr : expr MOD exprexpr : expr POW exppexpr : LBR expr RBRexpr : NUMexpr : SUB expn %prec NEGexpn : NUMexpn : LBR expr RBRexpp : expp ADD exppexpp : expp SUB exppexpp : expp MUL exppexpp : expp DIV exppexpp : expp MOD exppexpp : LBR expp RBRexpp : SUB exppn %prec NEGexppn : NUMexpp : NUM'
    
_lr_action_items = {'LBR':([0,2,3,5,6,7,8,9,10,13,22,26,27,28,29,30,],[3,13,3,3,3,3,3,3,22,3,22,22,22,22,22,22,]),'NUM':([0,2,3,5,6,7,8,9,10,13,21,22,26,27,28,29,30,],[4,12,4,4,4,4,4,4,23,4,32,23,23,23,23,23,23,]),'SUB':([0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[2,6,2,-8,2,2,2,2,2,21,-9,-10,2,6,-1,-2,-3,-4,-5,-6,21,-20,6,-7,21,21,21,21,21,-18,-19,27,-11,-12,-13,-14,-15,-16,-17,]),'$end':([1,4,11,12,15,16,17,18,19,20,23,25,31,32,34,35,36,37,38,39,40,],[0,-8,-9,-10,-1,-2,-3,-4,-5,-6,-20,-7,-18,-19,-11,-12,-13,-14,-15,-16,-17,]),'ADD':([1,4,11,12,14,15,16,17,18,19,20,23,24,25,31,32,33,34,35,36,37,38,39,40,],[5,-8,-9,-10,5,-1,-2,-3,-4,-5,-6,-20,5,-7,-18,-19,26,-11,-12,-13,-14,-15,-16,-17,]),'MUL':([1,4,11,12,14,15,16,17,18,19,20,23,24,25,31,32,33,34,35,36,37,38,39,40,],[7,-8,-9,-10,7,7,7,-3,-4,-5,-6,-20,7,-7,-18,-19,28,-11,28,28,-14,-15,-16,-17,]),'DIV':([1,4,11,12,14,15,16,17,18,19,20,23,24,25,31,32,33,34,35,36,37,38,39,40,],[8,-8,-9,-10,8,8,8,-3,-4,-5,-6,-20,8,-7,-18,-19,29,-11,29,29,-14,-15,-16,-17,]),'MOD':([1,4,11,12,14,15,16,17,18,19,20,23,24,25,31,32,33,34,35,36,37,38,39,40,],[9,-8,-9,-10,9,9,9,9,9,-5,-6,-20,9,-7,-18,-19,30,-11,30,30,30,30,-16,-17,]),'POW':([1,4,11,12,14,15,16,17,18,19,20,23,24,25,31,32,34,35,36,37,38,39,40,],[10,-8,-9,-10,10,10,10,10,10,-5,-6,-20,10,-7,-18,-19,-11,-12,-13,-14,-15,-16,-17,]),'RBR':([4,11,12,14,15,16,17,18,19,20,23,24,25,31,32,33,34,35,36,37,38,39,40,],[-8,-9,-10,25,-1,-2,-3,-4,-5,-6,-20,34,-7,-18,-19,40,-11,-12,-13,-14,-15,-16,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,5,6,7,8,9,13,],[1,14,15,16,17,18,19,24,]),'expn':([2,],[11,]),'expp':([10,22,26,27,28,29,30,],[20,33,35,36,37,38,39,]),'exppn':([21,],[31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr ADD expr','expr',3,'p_add','zad2.py',76),
  ('expr -> expr SUB expr','expr',3,'p_sub','zad2.py',80),
  ('expr -> expr MUL expr','expr',3,'p_mul','zad2.py',84),
  ('expr -> expr DIV expr','expr',3,'p_div','zad2.py',88),
  ('expr -> expr MOD expr','expr',3,'p_mod','zad2.py',92),
  ('expr -> expr POW expp','expr',3,'p_pow','zad2.py',96),
  ('expr -> LBR expr RBR','expr',3,'p_br','zad2.py',106),
  ('expr -> NUM','expr',1,'p_expr2NUM','zad2.py',109),
  ('expr -> SUB expn','expr',2,'p_expr2NEG','zad2.py',113),
  ('expn -> NUM','expn',1,'p_expr2NEG_NUM','zad2.py',117),
  ('expn -> LBR expr RBR','expn',3,'p_expr2NEG_BR','zad2.py',120),
  ('expp -> expp ADD expp','expp',3,'p_add_power','zad2.py',124),
  ('expp -> expp SUB expp','expp',3,'p_sub_power','zad2.py',128),
  ('expp -> expp MUL expp','expp',3,'p_mul_power','zad2.py',132),
  ('expp -> expp DIV expp','expp',3,'p_div_power','zad2.py',136),
  ('expp -> expp MOD expp','expp',3,'p_mod_power','zad2.py',140),
  ('expp -> LBR expp RBR','expp',3,'p_br_power','zad2.py',144),
  ('expp -> SUB exppn','expp',2,'p_expr2NEG_power','zad2.py',147),
  ('exppn -> NUM','exppn',1,'p_expr2NUM_power_neg','zad2.py',151),
  ('expp -> NUM','expp',1,'p_expr2NUM_power','zad2.py',154),
]
